app/assets/stylesheets/views/_header.scss
app/views/layouts/_global_header.haml
app/views/layouts/_header_anchors.haml

Make global header dropdown menus relative to their button container. 
Minimum dropdown menu width is smallest of either:
-  width of button container
-  largest text link contained
Buttons and links are sized relative to the height of the header and internal items are center aligned using flex.

Style global header

---

app/assets/stylesheets/main.scss
app/assets/stylesheets/mixins/_layout.scss
app/assets/stylesheets/mixins/type.scss
app/assets/stylesheets/partials/_texts.scss
app/assets/stylesheets/views/_header.scss
app/views/layouts/_head.haml

Change site body font-face to "Raleway". Larger text mixins are @comfortaa, site may require some refining to setup what is and is not a header and therefore comfortaa

Change site font to raleway

---

app/views/listings/form/_description.haml

Issue: https://www.wrike.com/open.htm?id=517080436

remove info for detailed description in new lising form

---

app/assets/stylesheets/views/_preauthorize.scss
app/views/listing_conversations/_stripe_payment.haml
app/views/listing_conversations/_you_will_be_charged_notice.haml
app/views/listing_conversations/_you_will_charged_notice.haml
app/views/listing_conversations/initiate.haml

Created partial with 'how payment works text': app/views/listing_conversations/_you_will_charged_notice.haml 
Called in existing position (initiate.haml) and requested new position (_stripe_payment.haml).

517076940 move text about how payment works

---

app/services/stripe_service/api/stripe_api_wrapper.rb
app/services/transaction_service/order.rb

**Task:** https://www.wrike.com/open.htm?id=517078671
**Issue:** Fix stripe payments errors
**Changes:**
- remove on_behalf_of payments from stripe wrapper, so all money is routed into application account. This should stop errors with transactions fees being too high etc
- remove some hardcoded dev environment
**Deploy:**
- restart applicaiton server
- remove stripe fees in admin settings after deploy

#517078671 stripe payment bug

---

app/views/layouts/application.haml

**Task:** https://www.wrike.com/open.htm?id=542244345
**Issue:** Add 15 second delay on mailchimp popup being rendered
**Changes:**
- Add timeout function for mailchimp popup in application view

#542244345 delay mailchimp popup

---

app/helpers/email_helper.rb
app/views/community_mailer/_community_update_listing.html.haml
app/views/community_mailer/community_updates.html.haml
app/views/layouts/email.html.haml
app/views/person_mailer/welcome_email.html.haml
config/environments/production.rb

**Task:** https://www.wrike.com/open.htm?id=474971716
**Issue:** Email images not prepending asset host
**Changes:** Add assets host url to production configuration and remove email_ur helper method since it is not required
**Deploy:** Restart application server

#474971716_email_images_fix

---

app/assets/javascripts/typed_slogan.js.es6
config/config.defaults.yml

**Task:** Client message
**Issue:** Typed slogan too fast
**Changes:** slow down typed slogan in javascript config, fix dev server host
**Deploy:** Recompile assets and restart application server

Slow down typed header

---

config/config.defaults.yml
config/locales/en.yml

**Task:** https://www.wrike.com/open.htm?id=539205927
**Issue:** Email text change
**Changes:** Change email text
**Deploy notes:** Restart application server

#539205927 change verify details email

---

app/assets/stylesheets/views/_listing-image-carousel.scss

**Task:** https://www.wrike.com/open.htm?id=544760925
**Issue:** Listing images not displaying
**Changes:** Remove letter spacing from listing images container to allow previous vertical centering image hack to work
**Deploy:** 
- recompile assets

#544760925_fix_broken_listing_images

---

app/assets/javascripts/admin/listing_shapes.js
app/assets/stylesheets/partials/_fluid-grid-listing-image.scss
app/assets/stylesheets/views/_home-thumbnail-grid.scss
app/assets/stylesheets/views/admin/_listing_shapes.scss
app/models/listing_shape.rb
app/view_utils/listing_index_view_utils.rb
app/view_utils/listing_shape_data_types.rb
app/view_utils/shape_service.rb
app/view_utils/translation_service_helper.rb
app/views/admin/listing_shapes/_shape_form_content.haml
app/views/admin/listing_shapes/edit.haml
app/views/admin/listing_shapes/new.haml
app/views/homepage/_grid_item.haml
app/views/layouts/_header_menu.haml
config/locales/en.yml
db/migrate/20200724231501_add_listing_color_to_listing_shapes.rb
db/migrate/20200725114710_add_listing_title_color_to_listing_shape.rb
db/structure.sql
spec/factories.rb
spec/models/listing_shape_spec.rb

**Task:** https://www.wrike.com/open.htm?id=530883614
**Issue:** Create color associations for each listing type on homepage
**Changes:** 
- Add listing_color and listing_title_color to listing_shape model and update form
- Add default border and background color styles
- Add dynamic inline styles for the custom color generated in views
- Add javascript hex verification and realtime update for client in admin changes
**Deploy notes:** 
- db:migrate
- Recompile static assets due to changes to JavaScript and styles,
- Restart application server

#530883614 listing shape color associations

---

app/assets/javascripts/admin/listing_shapes.js
app/assets/javascripts/kassi.js
app/assets/stylesheets/partials/_flash.scss
app/assets/stylesheets/partials/_fluid-grid-listing-image.scss
app/assets/stylesheets/views/_home-thumbnail-grid.scss
app/assets/stylesheets/views/admin/_listing_shapes.scss
app/models/listing_shape.rb
app/view_utils/listing_index_view_utils.rb
app/view_utils/listing_shape_data_types.rb
app/view_utils/shape_service.rb
app/view_utils/translation_service_helper.rb
app/views/admin/listing_shapes/_shape_form_content.haml
app/views/admin/listing_shapes/edit.haml
app/views/admin/listing_shapes/new.haml
app/views/homepage/_grid_item.haml
app/views/homepage/index.haml
app/views/layouts/_header_menu.haml
config/locales/en.yml
custom_scripts.html
db/migrate/20200724231501_add_listing_color_to_listing_shapes.rb
db/migrate/20200725114710_add_listing_title_color_to_listing_shape.rb
db/structure.sql
spec/factories.rb
spec/models/listing_shape_spec.rb

**Task:** https://www.wrike.com/open.htm?id=541335282
**Issue:** Update listing selection buttons to highlight listing color on hover, and create functionality for removing selection on click of already selected button
**Changes:**
- Add listing colors to listing button element as data attributes
- Create javascript functions for highlighting with correct color on hover
- Create javascript function to prevent default click if button already selected and remove search parameters
**Deploy:**
- This is dependant on Pull Request https://github.com/dignityplatform/sharetribe/pull/47 being already merged, please merge beforehand
- Recompile static assets since there are changes to styles and javascript
- Restart application server

#541335282 update listing type selection buttons

---

app/controllers/application_controller.rb
app/view_utils/listing_index_view_utils.rb
app/views/layouts/_header_menu.haml
config/locales/en.yml

Added how_to_use icon to pack: app/controllers/application_controller.rb
Added how_it_works header to locales/en.yml
Added menu item linking to infos/how_to_use near top of main drop down menu as per ticket 'Make 'How it works' easier to find #554855664'

Added How it Works to main menu, ticket #554855664

---

app/helpers/listings_helper.rb

557525540_add_listing_shape_name_to_list_view - fix regex error in helper

557525540_add_listing_shape_name_to_list_view - fix regex error in helper

---

app/views/layouts/_head.haml
app/views/layouts/application.haml

**Task:** https://www.wrike.com/open.htm?id=544933788
**Issue:** Mail chimp 404 error
**Changes:** 
- move mailchimp scripts to head
- add custom script with correct id and timeout function
**Deploy:**

544933788 fix mailchimp

---

config/config.defaults.yml

**Task:** https://www.wrike.com/open.htm?id=554856726
**Issue:** No display name on maketplace email
**Changes:**
- update application defaults display name
**Deploy:**
- check config.yml includes update or does not override defaults

554856726 update from email display name in config

---

app/assets/stylesheets/partials/_texts.scss

**Task:** https://www.wrike.com/open.htm?id=546027984
**Issue:** About text still in comfortaa
**Changes:**
- update heading 3,4,5,6 to be raleway font
**Deploy:**
- recompile assets
- edit about text to be correct formatting

546027984 change_font_about_page

---

app/assets/stylesheets/partials/_texts.scss
app/views/people/_followed_people.haml
app/views/people/show.haml
config/locales/en.yml

**Task:** https://www.wrike.com/open.htm?id=557412649
**Issue:** Make listing types on user profle clearer
**Changes:**
- Change text on user profile to client request
- Make following list private
**Deploy:**
-  recompile assets

557412649 change text on profiles

---

app/views/admin/community_transactions/show.haml
config/locales/en.yml

**Bug Fix** 
- admin transaction view error due to nil values for legacy transaction
**Deploy:**

512262652_fix_admin_view

---

app/views/layouts/_global_header.haml
app/views/layouts/_header_right.haml

**Task:** https://www.wrike.com/open.htm?id=557617019
**Issue:** Make inbox visibible on mobile
**Changes:**
- Update inbox to be visible on all platforms
**Deploy:**
  

update inbox to always be visibile in header right section

---

app/assets/stylesheets/main.scss

**Task:** https://www.wrike.com/open.htm?id=517072401
**Issue:** T&Cs popup very narrow on desktop
**Changes:**
- Change style to be closer to header width
**Deploy:**
- recompile assets

517072401_widen_tc_popup

---

app/views/layouts/_cause_layout.haml
config/config.defaults.yml
config/locales/en.yml

**Task:** https://www.wrike.com/open.htm?id=562826864
**Issue:** Some emails not sending
**Changes:**
- Add smtp defaults back into config
- Update production sendmail settings and host
- Update gigfunding cause (unrelated)
**Deploy:**
- Restart application server 

562826864 email bugs

---

app/assets/javascripts/kassi.js
app/assets/stylesheets/mixins/default-colors.scss
app/assets/stylesheets/views/_causes.scss
app/controllers/admin/causes_controller.rb
app/controllers/causes_controller.rb
app/controllers/infos_controller.rb
app/helpers/application_helper.rb
app/models/cause.rb
app/views/admin/causes/edit.haml
app/views/admin/causes/form/_extended_description.haml
app/views/admin/causes/form/_link.haml
app/views/admin/causes/new.haml
app/views/infos/_causes_content.haml
app/views/infos/cause_content/_clickable_cause.haml
app/views/infos/causes.haml
app/views/layouts/_header_menu.haml
config/locales/en.yml
config/routes.rb
db/migrate/20200918184345_add_extended_description_to_causes.rb
db/structure.sql
spec/models/cause_spec.rb

**Task:** https://www.wrike.com/open.htm?id=562747580
**Issue:** Create causes page
**Changes:**
- Add extended_description to causes
- Propagate new attribute through admin causes controller
- Add causes page to infos controller
- Add link to causes page in header menu
- Add causes selection to causes page
- Display selected cause extended_description on cause button click (markdown)
**Deploy:**
- recompile assets
 

562747580 causes page

---

config/environments/production.rb

**Task:** https://www.wrike.com/open.htm?id=562826864
**Issue:** Emails not working
**Changes:**
- Convert mailer to smtp from sendmail
- add ssl settings
**Deploy:**

562826864_add_ssl_to_smtp_settings

---

app/controllers/preauthorize_transactions_controller.rb
app/helpers/transaction_helper.rb
app/views/admin/community_transactions/_table.haml
app/views/admin/community_transactions/show.haml
spec/controllers/admin/community_listings_controller_spec.rb
spec/controllers/listings_controller_spec.rb
spec/helpers/transaction_helper_spec.rb
spec/mailers/person_mailer_spec.rb
spec/mailers/transaction_mailer_spec.rb
spec/spec_helper.rb

**Task:** https://www.wrike.com/open.htm?id=581538695
**Issue:** admin transactions area not rendering correct users
**Changes:**
- make view helper to return transaction starter and author
**Deploy:**

581538695 admin transactions bug

---

app/helpers/transaction_helper.rb
spec/helpers/transaction_helper_spec.rb

**Task:** https://www.wrike.com/open.htm?id=581538695
**Issue:** fix issue with free transactions
**Changes:**
- fix helper methods
**Deploy:**

581538695_admin_transactions_bug
